name = "DigitalAssetExchangeFormatIO"
uuid = "43182933-f65b-495a-9e05-4d939cea427d"
authors = ["Daniel Larby <dan_larby@hotmail.co.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
